/**
 * QA code: TS-WEB-003 response-clean · v1.1.0
 * Area: apps/web/src/lib/response-clean
 * Family: WEB
 */

import { describe, expect, it } from "vitest";
import { normalizeInterpretationPunctuation, stripInterpretationFluff } from "@/lib/response-clean";

describe("normalizeInterpretationPunctuation", () => {
  it("inserts space after comma before a letter", () => {
    expect(normalizeInterpretationPunctuation("sostiene,según la")).toBe("sostiene, según la");
    expect(normalizeInterpretationPunctuation("dirección,Seguir aquí")).toBe("dirección, Seguir aquí");
  });

  it("does not break decimal comma before digit", () => {
    expect(normalizeInterpretationPunctuation("valor 1,5 mm")).toBe("valor 1,5 mm");
  });

  it("fixes comma followed by period", () => {
    expect(normalizeInterpretationPunctuation("externas,. Si ella")).toBe("externas. Si ella");
  });

  it("inserts space after colon before letter without forcing uppercase", () => {
    expect(normalizeInterpretationPunctuation("tensión:el veredicto")).toBe("tensión: el veredicto");
    expect(normalizeInterpretationPunctuation("revela: la Reunión")).toBe("revela: la Reunión");
  });

  it("adds space before word after closing paren", () => {
    expect(normalizeInterpretationPunctuation("(45)Siguiente")).toBe("(45) Siguiente");
  });
});

describe("stripInterpretationFluff", () => {
  it("removes leading CATEGORY line with newline", () => {
    const raw = "CATEGORY: love_relationship\n\n## ENCUADRE\n\nBody";
    expect(stripInterpretationFluff(raw)).toContain("## ENCUADRE");
    expect(stripInterpretationFluff(raw)).not.toMatch(/CATEGORY/i);
  });

  it("removes leading CATEGORÍA line when slug is on its own line", () => {
    const raw = "CATEGORÍA: general\r\n## Título";
    const out = stripInterpretationFluff(raw);
    expect(out).not.toMatch(/CATEGOR/i);
    expect(out).toContain("## Título");
  });

  // Regression (2026-08): a trailing copyright/rights/domain signature the model sometimes
  // appends must be hidden from every DISPLAY surface (chat, PDF, public share pages), but
  // the check must never remove any part of the real reading. This is display-time only:
  // the stored consultation text is untouched (see backend/claude/src/response-clean.ts).
  describe("trailing signature clause (display-only suppression)", () => {
    it("strips a note glued onto the end of the last sentence, no blank line", () => {
      const raw =
        "El oráculo, Alexis, no dice que tus posibilidades han desaparecido. Dice algo más preciso. Generado por theoriginaliching.com";
      expect(stripInterpretationFluff(raw)).toBe(
        "El oráculo, Alexis, no dice que tus posibilidades han desaparecido. Dice algo más preciso.",
      );
    });

    it("strips a note on its own paragraph with no italics (the old regex required italics)", () => {
      const raw =
        "## Horizonte y síntesis\n\nEsta es la lectura completa del oráculo para tu situación.\n\n© 2026 theoriginaliching.com";
      expect(stripInterpretationFluff(raw)).toBe(
        "## Horizonte y síntesis\n\nEsta es la lectura completa del oráculo para tu situación.",
      );
    });

    it("strips an English trailing note glued to the last sentence", () => {
      const raw =
        "The oracle speaks of patience and careful timing before any decisive action. Generated by theoriginaliching.com";
      expect(stripInterpretationFluff(raw)).toBe(
        "The oracle speaks of patience and careful timing before any decisive action.",
      );
    });

    it("strips a Spanish rights-reserved phrase glued to the last sentence", () => {
      const raw =
        "El oráculo cierra esta lectura con una invitación a la calma y la introspección profunda. Todos los derechos reservados.";
      expect(stripInterpretationFluff(raw)).toBe(
        "El oráculo cierra esta lectura con una invitación a la calma y la introspección profunda.",
      );
    });

    it("only touches the last paragraph: an earlier section stays intact", () => {
      const raw =
        "## El juicio\n\nEste es el juicio clásico aplicado a tu pregunta con todo detalle.\n\n## Horizonte y síntesis\n\nUn paso concreto: mantén la calma. theoriginaliching.com";
      expect(stripInterpretationFluff(raw)).toBe(
        "## El juicio\n\nEste es el juicio clásico aplicado a tu pregunta con todo detalle.\n\n## Horizonte y síntesis\n\nUn paso concreto: mantén la calma.",
      );
    });

    // The critical safety case: a real short closing sentence immediately followed (same
    // paragraph, no blank line) by the disclaimer must lose ONLY the disclaimer sentence,
    // never the real sentence in front of it.
    it("never removes a real short sentence that precedes the glued signature", () => {
      const raw = "## Horizonte y síntesis\n\nUn paso concreto: mantén la calma. theoriginaliching.com";
      const out = stripInterpretationFluff(raw);
      expect(out).toContain("Un paso concreto: mantén la calma.");
      expect(out).not.toMatch(/theoriginaliching\.com/i);
    });

    it("leaves a normal multi-sentence paragraph fully untouched when no trigger is present", () => {
      const raw =
        "El oráculo, Alexis, no dice que tus posibilidades han desaparecido. Dice algo más preciso y más exigente. El momento actual es de bloqueo real entre las fuerzas que deberían facilitar tu continuidad.";
      expect(stripInterpretationFluff(raw)).toBe(raw);
    });

    it("leaves a short standalone closing sentence untouched when it has no trigger", () => {
      const raw = "## Horizonte y síntesis\n\nUn paso concreto: mantén la calma.";
      expect(stripInterpretationFluff(raw)).toBe(raw);
    });

    it("leaves an organic mid-sentence domain mention untouched (too much real prose around it)", () => {
      const raw =
        "El oráculo dice que theoriginaliching.com y su comunidad han visto patrones similares antes, y que ese mismo territorio es donde llegará la ayuda inesperada que buscas en este momento de tu vida.";
      expect(stripInterpretationFluff(raw)).toBe(raw);
    });

    it("leaves a short paragraph that organically uses a trigger word as real content", () => {
      const raw =
        "## Horizonte y síntesis\n\nMantén tus recursos reservados para el momento oportuno de actuar con determinación.";
      expect(stripInterpretationFluff(raw)).toBe(raw);
    });

    it("never collapses to an empty reading when the whole text is just the trigger with nothing before it", () => {
      expect(stripInterpretationFluff("theoriginaliching.com")).toBe("theoriginaliching.com");
    });
  });
});
