/**
 * QA code: TS-WEB-018 rights-line-paragraph-length-gate · v1.0.0
 * Area: apps/web/src/components/OracleInterpretationMarkdown
 * Family: WEB
 */

import { describe, expect, it } from "vitest";
import { isRightsReservedParagraph } from "@/components/OracleInterpretationMarkdown";

describe("isRightsReservedParagraph", () => {
  it("still flags a real standalone copyright line (the common case)", () => {
    expect(isRightsReservedParagraph("© 2026 The Original I Ching · theoriginaliching.com")).toBe(true);
  });

  it("still flags a short standalone site-generated note", () => {
    expect(isRightsReservedParagraph("Generated by theoriginaliching.com")).toBe(true);
  });

  it("still flags multilingual rights-reserved phrasing", () => {
    expect(isRightsReservedParagraph("Todos los derechos reservados.")).toBe(true);
  });

  it("does NOT flag a normal content paragraph with no trigger phrase", () => {
    const p =
      "El oráculo, Alexis, no dice que tus posibilidades han desaparecido. Dice algo más " +
      "preciso y más exigente: dice que el momento actual es de bloqueo real entre las " +
      "fuerzas que deberían facilitar tu continuidad en Canadá.";
    expect(isRightsReservedParagraph(p)).toBe(false);
  });

  // Regression: the model can glue its closing disclaimer onto the same paragraph as real
  // content with no blank line in between, which is common on the long free-form closing
  // paragraph in Master Combined mode. Before the length gate, the WHOLE paragraph lost
  // justification because the classifier matched the trigger substring anywhere in the text.
  it("does NOT flag a long paragraph even when a trigger phrase is glued onto its end", () => {
    const p =
      "El oráculo, Alexis, no dice que tus posibilidades han desaparecido. Dice algo más " +
      "preciso y más exigente: dice que el momento actual es de bloqueo real entre las " +
      "fuerzas que deberían facilitar tu continuidad en Canadá, y que luchar de frente " +
      "contra ese bloqueo con los métodos habituales puede no ser lo más eficaz. " +
      "Generado por theoriginaliching.com";
    expect(isRightsReservedParagraph(p)).toBe(false);
  });

  it("does NOT flag a long paragraph that merely mentions the domain organically", () => {
    const p =
      "El oráculo, Alexis, no dice que tus posibilidades han desaparecido. Dice algo más " +
      "preciso y más exigente: dice que theoriginaliching.com y su comunidad han visto " +
      "patrones similares antes, y que ese mismo territorio es donde llegará la ayuda.";
    expect(isRightsReservedParagraph(p)).toBe(false);
  });

  it("returns false for empty input", () => {
    expect(isRightsReservedParagraph("")).toBe(false);
    expect(isRightsReservedParagraph("   ")).toBe(false);
  });
});
