/**
 * Compact hexagram glyph data for the marketing hero canvas animation.
 * Generated from packages/iching-data (Baynes EN names) + the design export ES
 * names (2026-07-11). Decorative marketing data only — the oracle corpus lives
 * in @iching-oracle/iching-data.
 */
export type HexGlyph = { n: number; ch: string; pin: string; es: string; en: string; bin: string };

export const HEX_GLYPHS: HexGlyph[] = [
  {"n":1,"ch":"乾","pin":"qián","es":"Lo Creativo","en":"The Creative","bin":"111111"},
  {"n":2,"ch":"坤","pin":"kūn","es":"Lo Receptivo","en":"The Receptive","bin":"000000"},
  {"n":3,"ch":"屯","pin":"zhūn","es":"La Dificultad Inicial","en":"Difficulty at the Beginning","bin":"010001"},
  {"n":4,"ch":"蒙","pin":"méng","es":"La Necedad Juvenil","en":"Youthful Folly","bin":"100010"},
  {"n":5,"ch":"需","pin":"xū","es":"La Espera","en":"Waiting (Nourishment)","bin":"010111"},
  {"n":6,"ch":"訟","pin":"sòng","es":"El Conflicto","en":"Conflict","bin":"111010"},
  {"n":7,"ch":"師","pin":"shī","es":"El Ejército","en":"The Army","bin":"000010"},
  {"n":8,"ch":"比","pin":"bǐ","es":"La Solidaridad","en":"Holding Together [Union]","bin":"010000"},
  {"n":9,"ch":"小畜","pin":"xiǎochù","es":"La Fuerza Domesticadora de lo Pequeño","en":"The Taming Power of the Small","bin":"110111"},
  {"n":10,"ch":"履","pin":"lǚ","es":"El Porte","en":"Treading [Conduct]","bin":"111011"},
  {"n":11,"ch":"泰","pin":"tài","es":"La Paz","en":"Peace","bin":"000111"},
  {"n":12,"ch":"否","pin":"pǐ","es":"El Estancamiento","en":"Standstill [Stagnation]","bin":"111000"},
  {"n":13,"ch":"同人","pin":"tóngrén","es":"Comunidad con los Hombres","en":"Fellowship with Men","bin":"111101"},
  {"n":14,"ch":"大有","pin":"dàyǒu","es":"La Posesión de lo Grande","en":"Posession in Great Measure","bin":"101111"},
  {"n":15,"ch":"謙","pin":"qiān","es":"La Modestia","en":"Modesty","bin":"000100"},
  {"n":16,"ch":"豫","pin":"yù","es":"El Entusiasmo","en":"Enthusiasm","bin":"001000"},
  {"n":17,"ch":"隨","pin":"suí","es":"El Seguimiento","en":"Following","bin":"011001"},
  {"n":18,"ch":"蠱","pin":"gǔ","es":"El Trabajo en lo Echado a Perder","en":"Work on What Has Been Spoiled [Decay]","bin":"100110"},
  {"n":19,"ch":"臨","pin":"lín","es":"El Acercamiento","en":"Approach","bin":"000011"},
  {"n":20,"ch":"觀","pin":"guān","es":"La Contemplación","en":"Contemplation (View)","bin":"110000"},
  {"n":21,"ch":"噬嗑","pin":"shìkè","es":"La Mordedura Tajante","en":"Biting Through","bin":"101001"},
  {"n":22,"ch":"賁","pin":"bì","es":"La Gracia","en":"Grace","bin":"100101"},
  {"n":23,"ch":"剝","pin":"bō","es":"La Desintegración","en":"Splitting Apart","bin":"100000"},
  {"n":24,"ch":"復","pin":"fù","es":"El Retorno","en":"Return (The Turning Point)","bin":"000001"},
  {"n":25,"ch":"無妄","pin":"wúwàng","es":"La Inocencia","en":"Innocence (The Unexpected)","bin":"111001"},
  {"n":26,"ch":"大畜","pin":"dàchù","es":"La Fuerza Domesticadora de lo Grande","en":"The Taming Power of the Great","bin":"100111"},
  {"n":27,"ch":"頤","pin":"yí","es":"La Nutrición","en":"The Corners of the Mouth","bin":"100001"},
  {"n":28,"ch":"大過","pin":"dàguò","es":"La Preponderancia de lo Grande","en":"Preponderance of the Great","bin":"011110"},
  {"n":29,"ch":"坎","pin":"kǎn","es":"Lo Abismal, el Agua","en":"The Abysmal (Water)","bin":"010010"},
  {"n":30,"ch":"離","pin":"lí","es":"Lo Adherente, el Fuego","en":"The Clinging, Fire","bin":"101101"},
  {"n":31,"ch":"咸","pin":"xián","es":"El Influjo","en":"Influence (Wooing)","bin":"011100"},
  {"n":32,"ch":"恆","pin":"héng","es":"La Duración","en":"Duration","bin":"001110"},
  {"n":33,"ch":"遁","pin":"dùn","es":"La Retirada","en":"Retreat","bin":"111100"},
  {"n":34,"ch":"大壯","pin":"dàzhuàng","es":"El Poder de lo Grande","en":"The Power of the Great","bin":"001111"},
  {"n":35,"ch":"晉","pin":"jìn","es":"El Progreso","en":"Progress","bin":"101000"},
  {"n":36,"ch":"明夷","pin":"míngyí","es":"El Oscurecimiento de la Luz","en":"Darkening of the Light","bin":"000101"},
  {"n":37,"ch":"家人","pin":"jiārén","es":"El Clan","en":"The Family [The Clan]","bin":"110101"},
  {"n":38,"ch":"睽","pin":"kuí","es":"El Antagonismo","en":"Opposition","bin":"101011"},
  {"n":39,"ch":"蹇","pin":"jiǎn","es":"El Impedimento","en":"Obstruction","bin":"010100"},
  {"n":40,"ch":"解","pin":"xiè","es":"La Liberación","en":"Deliverance","bin":"001010"},
  {"n":41,"ch":"損","pin":"sǔn","es":"La Merma","en":"Decrease","bin":"100011"},
  {"n":42,"ch":"益","pin":"yì","es":"El Aumento","en":"Increase","bin":"110001"},
  {"n":43,"ch":"夬","pin":"guài","es":"La Resolución","en":"Break-through (Resoluteness)","bin":"011111"},
  {"n":44,"ch":"姤","pin":"gòu","es":"El Ir al Encuentro","en":"Coming to Meet","bin":"111110"},
  {"n":45,"ch":"萃","pin":"cuì","es":"La Reunión","en":"Gathering Together [Massing]","bin":"011000"},
  {"n":46,"ch":"升","pin":"shēng","es":"La Subida","en":"Pushing Upward","bin":"000110"},
  {"n":47,"ch":"困","pin":"kùn","es":"El Agotamiento","en":"Oppression (Exhaustion)","bin":"011010"},
  {"n":48,"ch":"井","pin":"jǐng","es":"El Pozo","en":"The Well","bin":"010110"},
  {"n":49,"ch":"革","pin":"gé","es":"La Revolución","en":"Revolution (Molting)","bin":"011101"},
  {"n":50,"ch":"鼎","pin":"dǐng","es":"El Caldero","en":"The Caldron","bin":"101110"},
  {"n":51,"ch":"震","pin":"zhèn","es":"Lo Suscitativo, el Trueno","en":"The Arousing (Shock, Thunder)","bin":"001001"},
  {"n":52,"ch":"艮","pin":"gèn","es":"El Aquietamiento, la Montaña","en":"Keeping Still, Mountain","bin":"100100"},
  {"n":53,"ch":"漸","pin":"jiàn","es":"La Evolución","en":"Development (Gradual Progress)","bin":"110100"},
  {"n":54,"ch":"歸妹","pin":"guīmèi","es":"La Muchacha que se Casa","en":"The Marrying Maiden","bin":"001011"},
  {"n":55,"ch":"豐","pin":"fēng","es":"La Plenitud","en":"Abundance [Fullness]","bin":"001101"},
  {"n":56,"ch":"旅","pin":"lǚ","es":"El Andariego","en":"The Wanderer","bin":"101100"},
  {"n":57,"ch":"巽","pin":"xùn","es":"Lo Suave, el Viento","en":"The Gentle (Penetrating, Wind)","bin":"110110"},
  {"n":58,"ch":"兌","pin":"duì","es":"Lo Sereno, el Lago","en":"The Joyous, Lake","bin":"011011"},
  {"n":59,"ch":"渙","pin":"huàn","es":"La Disolución","en":"Dispersion [Dissolution]","bin":"110010"},
  {"n":60,"ch":"節","pin":"jié","es":"La Restricción","en":"Limitation","bin":"010011"},
  {"n":61,"ch":"中孚","pin":"zhōngfú","es":"La Verdad Interior","en":"Inner Truth","bin":"110011"},
  {"n":62,"ch":"小過","pin":"xiǎoguò","es":"La Preponderancia de lo Pequeño","en":"Preponderance of the Small","bin":"001100"},
  {"n":63,"ch":"既濟","pin":"jìjì","es":"Después de la Consumación","en":"After Completion","bin":"010101"},
  {"n":64,"ch":"未濟","pin":"wèijì","es":"Antes de la Consumación","en":"Before Completion","bin":"101010"},
];
